# Generated by Django 6.0.5 on 2026-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('occupancy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Filling Fast', 'Filling Fast'), ('Full', 'Full'), ('Needs Supplies', 'Needs Supplies')], default='Available', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
