# Generated by Django 6.0.5 on 2026-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='longitude',
        ),
        migrations.AddField(
            model_name='shelter',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
