# Generated by Django 6.0.6 on 2026-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('district', models.CharField(choices=[('alappuzha', 'Alappuzha'), ('ernakulam', 'Ernakulam'), ('idukki', 'Idukki'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('kollam', 'Kollam'), ('kottayam', 'Kottayam'), ('kozhikode', 'Kozhikode'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('pathanamthitta', 'Pathanamthitta'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thrissur', 'Thrissur'), ('wayanad', 'Wayanad')], max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('availability', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
