# Generated by Django 6.0.5 on 2026-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='urgency_level',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Urgent', 'Urgent'), ('Life Threat', 'Life Threat')], default='Standard', max_length=20),
        ),
    ]
