# Generated by Django 6.0.5 on 2026-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
