# Generated by Django 6.0.5 on 2026-06-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_brakingnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrakingNew',
            new_name='BrakingNews',
        ),
    ]
