# Generated by Django 6.0.5 on 2026-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_brakingnew_brakingnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brakingnews',
            name='category',
            field=models.CharField(choices=[('Red Alert', 'Red Alert'), ('Weather Alert', 'Weather Alert'), ('Breaking News', 'Breaking News')], default='Breaking News', max_length=100),
        ),
    ]
